version: '3.8'
services:
  db:
    build:
      context: ./backend/database
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test4
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d test4"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./backend
    environment:
      DB: postgresql://myuser:mypassword@db:5432/test4
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app 


volumes:
  postgres_data: